version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    ports:
      - "5432:5432"
    env_file:
      - .env # configure postgres
    volumes:
      - ./database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./src/db/scripts.sql:/docker-entrypoint-initdb.d/scripts.sql # init script

volumes:
  database-data: # named volumes can be managed easier using docker-compose
